### ISSUE TITLE
this is my error plz help

### ISSUE THREAD

**Issue by yosoloman** [Trombov/FutureNNAimbot#35]
Unhandled Exception: System.DllNotFoundException: Microsoft Visual C++ 2017 Redistributable (x64)
   at Alturos.Yolo.YoloWrapper.Initialize(String configurationFilename, String weightsFilename, String namesFilename, Int32 gpu, Boolean ignoreGpu)
   at FutureNNAimbot.Program.Main(String[] args)

**Comment by Neakita** [comment]
https://github.com/Trombov/FutureNNAimbot/issues/31

**Comment by C-hrl** [comment]
[VCRedistCorrectedDLL.zip](https://github.com/Trombov/FutureNNAimbot/files/4970778/VCRedistCorrectedDLL.zip)
here is the fix, replace the original file in FNN with the one in the zip.
You may want to remove or close this issue now if my fix does the trick as I already opened an issue and corrected it in the past.
Also please, next time write a concise title and check for existing issues (and don't write a 100 messages on another post!!!! my github account is linked to a very bad pro mailbox for my work and I have to delete one mail at a time which means that now I have to delete a 100 mails ....), this is not a chatroom or discord.

**Comment by yosoloman** [comment]
Unhandled Exception: System.TypeLoadException: Could not load type 'Alturos.Yolo.GpuConfig' from assembly 'Alturos.Yolo, Version=2.4.1.0, Culture=neutral, PublicKeyToken=null'.
   at FutureNNAimbot.Program.Main(String[] args)

**Comment by yosoloman** [comment]
now this error

**Comment by C-hrl** [comment]
You can close this thread too as the error is different, maybe delete the entire thread as it's a doublon ? And please, if you can, change the title. I'll now mute github so good luck with your issues but I am tired of wasting 30 mins deleting mails ....
